### ISSUE TITLE
Error XFC0000: Cannot resolve type "sharpnado:MaterialFrame"

### ISSUE THREAD

**Issue by roubachof** [roubachof/Sharpnado.MaterialFrame#13]
If you end up with this error, it means you forgot to call the Sharpnado.MaterialFrame.Initializer.Initialize() in your App.xaml.cs.
Have a look here: https://github.com/roubachof/Sharpnado.MaterialFrame#initialization

**Comment by AliToghiany** [comment]
Sharpnado.MaterialFrame.Initializer.Initialize(false,false)
Hi, I wrote the above code, but it gives the same error @roubachof

**Comment by anversoft** [comment]
EDIT: If you are using a dependency injection framework like Prism just insert a function anywhere in the module that calls the initialize method.

`
 private static void DummyInitializer() => Sharpnado.MaterialFrame.Initializer.Initialize(true, false);
`


This happens because in the order of compilation of dependencies in a Prism project the Initialize function is called last and consequently the XFC0000 error is generated.

**Comment by louisoftokyo** [comment]
I'm getting this issue, but neither of the above fixes are working.
